// 设计/后台管理系统界面设计/src/app/LoginPage.tsx
import { useState } from "react";
import {
  Eye, EyeOff, AlertCircle, Loader2, FlaskConical, ChevronRight,
  Bot, Globe2, Bug, FileText, Timer, Activity,
} from "lucide-react";

// ─── Palette ──────────────────────────────────────────────────────────────────
const PNL  = "#0D1117";   // dark panel
const CARD = "#161B22";   // dark card
const DBR  = "#21262D";   // dark card border
const TEXT = "#E6EDF3";   // dark text
const MTD  = "#7D8590";   // dark muted
const BLU  = "#165DFF";   // accent
const LBR  = "#E5E6EB";   // light border
const LT1  = "#1D2129";   // light text-1
const LT3  = "#86909C";   // light text-3

const LOG_C: Record<string, string> = {
  ok: "#3FB950", fail: "#F85149", warn: "#E3B341",
  ai: "#A78BFA", dim: "#7D8590", sum: "#79C0FF",
};

// ─── Static data ──────────────────────────────────────────────────────────────
const FEATURES = [
  { icon: Bot,      label: "AI 用例生成",   desc: "需求驱动，自动生成",  col: "#8B5CF6" },
  { icon: Globe2,   label: "接口自动化",    desc: "场景化测试套件执行",  col: BLU       },
  { icon: Activity, label: "Web UI 自动化", desc: "录制 + AI 优化断言",  col: "#10B981" },
  { icon: Bug,      label: "缺陷追踪",      desc: "发现到修复全流程",    col: "#EF4444" },
  { icon: Timer,    label: "任务调度",      desc: "定时执行和历史查看",  col: "#F59E0B" },
  { icon: FileText, label: "智能报告",      desc: "多维度数据可视化",    col: "#06B6D4" },
];

const LOG = [
  { t: "dim",  s: "# 2026-07-07 14:30:01  触发: 定时调度" },
  { t: "ok",   s: "✓  POST /api/v1/orders            200  142ms" },
  { t: "ok",   s: "✓  GET  /api/v1/orders/list       200   89ms" },
  { t: "ok",   s: "✓  PUT  /api/v1/orders/status     200  204ms" },
  { t: "fail", s: "✗  DELETE /api/v1/orders/52       500 3021ms" },
  { t: "warn", s: "△  超时 > 3s，已推送企业微信告警通知" },
  { t: "ai",   s: "◆  AI 分析: 建议增加重试断言，生成 3 个边界用例" },
  { t: "sum",  s: "▸  通过 47/48  失败 1  耗时 4m 22s" },
];

const WORKSPACES = [
  { id: "w1", name: "X-MAN",   desc: "电商平台 · 订单/风控全链路自动化",  members: 8,  role: "测试负责人", recent: true,  lastVisit: "今天 09:31" },
  { id: "w2", name: "KRATOS",  desc: "风控中台 · 规则引擎和策略测试",      members: 12, role: "测试工程师", recent: false, lastVisit: "3 天前" },
  { id: "w3", name: "MINERVA", desc: "数据平台 · BI 报表和数据质量测试",   members: 5,  role: "只读访客",   recent: false, lastVisit: "7 天前" },
];

const WS_COLORS = [BLU, "#8B5CF6", "#10B981"];

// ─── Custom checkbox ──────────────────────────────────────────────────────────
function Checkbox({ on, onChange }: { on: boolean; onChange: () => void }) {
  return (
    <div onClick={onChange}
      className="w-4 h-4 rounded flex items-center justify-center flex-shrink-0 cursor-pointer transition-all"
      style={{ border: `2px solid ${on ? BLU : "#C9CDD4"}`, backgroundColor: on ? BLU : "transparent" }}>
      {on && (
        <svg width="9" height="7" viewBox="0 0 9 7" fill="none">
          <path d="M1 3.5L3.2 5.5L8 1" stroke="#fff" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      )}
    </div>
  );
}

// ─── Workspace selection ──────────────────────────────────────────────────────
function WorkspaceSelect({ onEnter, onBack }: { onEnter: () => void; onBack: () => void }) {
  return (
    <div className="h-screen flex flex-col items-center justify-center"
      style={{ backgroundColor: "#F4F6FA", fontFamily: "'Inter','PingFang SC',sans-serif" }}>

      {/* Logo */}
      <div className="flex items-center gap-2.5 mb-10">
        <div className="w-9 h-9 rounded-xl flex items-center justify-center"
          style={{ background: `linear-gradient(135deg,${BLU},#4F8EFF)` }}>
          <FlaskConical size={17} color="#fff" />
        </div>
        <span className="text-[17px] font-bold" style={{ color: LT1 }}>AutoTest</span>
      </div>

      <div className="text-center mb-8">
        <h2 className="text-[22px] font-semibold mb-1.5" style={{ color: LT1 }}>选择工作区</h2>
        <p className="text-[13px]" style={{ color: LT3 }}>你的账号下有 {WORKSPACES.length} 个工作区</p>
      </div>

      <div className="flex flex-col gap-3" style={{ width: 660 }}>
        {WORKSPACES.map((ws, idx) => (
          <button key={ws.id} onClick={onEnter}
            className="bg-white rounded-2xl text-left flex items-center gap-4 transition-all"
            style={{ padding: "20px 24px", border: `1px solid ${LBR}`, boxShadow: "0 1px 4px rgba(0,0,0,0.04)", cursor: "pointer", width: "100%" }}
            onMouseEnter={e => {
              const b = e.currentTarget as HTMLButtonElement;
              b.style.borderColor = BLU;
              b.style.boxShadow = "0 4px 20px rgba(22,93,255,0.12)";
            }}
            onMouseLeave={e => {
              const b = e.currentTarget as HTMLButtonElement;
              b.style.borderColor = LBR;
              b.style.boxShadow = "0 1px 4px rgba(0,0,0,0.04)";
            }}>
            <div className="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 text-white font-bold text-[16px]"
              style={{ background: `linear-gradient(135deg,${WS_COLORS[idx % WS_COLORS.length]},${WS_COLORS[idx % WS_COLORS.length]}BB)` }}>
              {ws.name[0]}
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-[15px] font-semibold" style={{ color: LT1 }}>{ws.name}</span>
                {ws.recent && (
                  <span className="text-[10px] px-2 py-0.5 rounded-full font-medium"
                    style={{ backgroundColor: "#E8F3FF", color: BLU }}>最近访问</span>
                )}
                <span className="text-[10px] px-2 py-0.5 rounded-full"
                  style={{ backgroundColor: "#F2F3F5", color: LT3 }}>{ws.role}</span>
              </div>
              <div className="text-[12px] mb-1.5" style={{ color: LT3 }}>{ws.desc}</div>
              <div className="flex items-center gap-4 text-[11px]" style={{ color: "#C9CDD4" }}>
                <span>{ws.members} 名成员</span>
                <span>上次访问 {ws.lastVisit}</span>
              </div>
            </div>
            <ChevronRight size={16} color="#C9CDD4" />
          </button>
        ))}

        <button className="rounded-2xl text-[13px] transition-all"
          style={{ padding: "14px 24px", border: `1.5px dashed ${LBR}`, background: "transparent", color: LT3, cursor: "pointer" }}
          onMouseEnter={e => { const b = e.currentTarget as HTMLButtonElement; b.style.borderColor = BLU; b.style.color = BLU; }}
          onMouseLeave={e => { const b = e.currentTarget as HTMLButtonElement; b.style.borderColor = LBR; b.style.color = LT3; }}>
          + 创建新工作区 或 申请加入其他工作区
        </button>
      </div>

      <div className="mt-8 text-[12px]" style={{ color: "#C9CDD4" }}>
        不是你的账号？
        <button onClick={onBack}
          style={{ color: BLU, background: "none", border: "none", cursor: "pointer", fontSize: 12, marginLeft: 4 }}>
          退出登录
        </button>
      </div>
    </div>
  );
}

// ─── Login page ───────────────────────────────────────────────────────────────
export function LoginPage({ onLogin }: { onLogin: () => void }) {
  const [view, setView]         = useState<"login" | "workspace">("login");
  const [account, setAccount]   = useState("");
  const [password, setPassword] = useState("");
  const [remember, setRemember] = useState(false);
  const [showPw, setShowPw]     = useState(false);
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState("");
  const [aErr, setAErr]         = useState("");
  const [pErr, setPErr]         = useState("");

  const handleLogin = () => {
    let ok = true;
    if (!account.trim()) { setAErr("请输入账号"); ok = false; } else setAErr("");
    if (!password.trim()) { setPErr("请输入密码"); ok = false; } else setPErr("");
    if (!ok) return;
    setError("");
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      if (password === "wrong") {
        setError("账号或密码错误，请检查后重试");
      } else {
        setView("workspace");
      }
    }, 1600);
  };

  const inputStyle = (hasErr: boolean, focused = false) => ({
    border: `1px solid ${hasErr ? "#F53F3F" : focused ? BLU : LBR}`,
    color: LT1, outline: "none", width: "100%", backgroundColor: "#fff",
    boxShadow: focused ? `0 0 0 3px ${hasErr ? "#F53F3F" : BLU}18` : "none",
  });

  if (view === "workspace") {
    return <WorkspaceSelect onEnter={onLogin} onBack={() => { setView("login"); setPassword(""); setError(""); }} />;
  }

  return (
    <div className="h-screen flex overflow-hidden"
      style={{ fontFamily: "'Inter','PingFang SC','Microsoft YaHei',sans-serif", fontSize: 14 }}>

      {/* ── Left dark panel ────────────────────────────────────────────── */}
      <div className="flex flex-col h-full" style={{ width: "58%", backgroundColor: PNL, padding: "44px 52px" }}>

        {/* Logo row */}
        <div className="flex items-center gap-2.5 mb-12">
          <div className="w-9 h-9 rounded-xl flex items-center justify-center"
            style={{ background: `linear-gradient(135deg,${BLU},#4F8EFF)` }}>
            <FlaskConical size={18} color="#fff" />
          </div>
          <span className="text-[18px] font-bold" style={{ color: TEXT }}>AutoTest</span>
          <span className="ml-1 text-[10px] px-2 py-0.5 rounded font-mono"
            style={{ backgroundColor: DBR, color: MTD, border: "1px solid #30363D" }}>v2.4.1</span>
        </div>

        {/* Headline */}
        <div className="mb-10">
          <h1 className="text-[27px] font-semibold leading-tight mb-3" style={{ color: TEXT }}>
            工程效率，<br />从测试开始
          </h1>
          <p className="text-[14px] leading-relaxed" style={{ color: MTD, maxWidth: 360 }}>
            AI 驱动的企业级自动化测试平台，<br />让质量保障不再成为交付的瓶颈
          </p>
        </div>

        {/* Feature grid */}
        <div className="grid grid-cols-2 gap-2.5 mb-7">
          {FEATURES.map(f => (
            <div key={f.label} className="flex items-center gap-3 p-3 rounded-xl"
              style={{ backgroundColor: CARD, border: `1px solid ${DBR}` }}>
              <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                style={{ backgroundColor: `${f.col}22` }}>
                <f.icon size={14} style={{ color: f.col }} />
              </div>
              <div>
                <div className="text-[12px] font-medium" style={{ color: TEXT }}>{f.label}</div>
                <div className="text-[11px]" style={{ color: MTD }}>{f.desc}</div>
              </div>
            </div>
          ))}
        </div>

        {/* Terminal log */}
        <div className="flex-1 rounded-xl overflow-hidden flex flex-col"
          style={{ backgroundColor: "#010409", border: `1px solid ${DBR}` }}>
          {/* Title bar */}
          <div className="flex items-center gap-1.5 px-4 py-2.5 flex-shrink-0"
            style={{ backgroundColor: CARD, borderBottom: `1px solid ${DBR}` }}>
            <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: "#F85149" }} />
            <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: "#E3B341" }} />
            <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: "#3FB950" }} />
            <span className="ml-3 text-[11px] font-mono" style={{ color: MTD }}>execution.log</span>
            <span className="ml-auto text-[10px] px-2 py-0.5 rounded font-mono"
              style={{ backgroundColor: "#1B2A1B", color: "#3FB950", border: "1px solid #2EA043" }}>● LIVE</span>
          </div>
          {/* Log lines */}
          <div className="flex-1 p-4 flex flex-col gap-1 overflow-hidden" style={{ fontFamily: "'JetBrains Mono','Fira Code',monospace", fontSize: 11 }}>
            {LOG.map((line, i) => (
              <div key={i} style={{ color: LOG_C[line.t] }}>{line.s}</div>
            ))}
          </div>
        </div>

        {/* Stats strip */}
        <div className="flex items-center gap-8 mt-5">
          {[
            { label: "今日执行",   value: "236 次",  color: TEXT },
            { label: "整体通过率", value: "93.6%",   color: "#3FB950" },
            { label: "在线 Runner",value: "6 个",    color: "#79C0FF" },
          ].map((s, i) => (
            <div key={i}>
              <div className="text-[17px] font-bold" style={{ color: s.color }}>{s.value}</div>
              <div className="text-[10px] mt-0.5" style={{ color: MTD }}>{s.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* ── Right form panel ────────────────────────────────────────────── */}
      <div className="flex flex-col items-center justify-center h-full"
        style={{ width: "42%", backgroundColor: "#fff" }}>
        <div style={{ width: "100%", maxWidth: 360, padding: "0 40px" }}>

          {/* Top platform mark */}
          <div className="flex items-center gap-2 mb-10">
            <div className="w-7 h-7 rounded-lg flex items-center justify-center"
              style={{ background: `linear-gradient(135deg,${BLU},#4F8EFF)` }}>
              <FlaskConical size={13} color="#fff" />
            </div>
            <span className="text-[13px] font-semibold" style={{ color: LT1 }}>AutoTest</span>
          </div>

          <h2 className="text-[24px] font-semibold mb-1.5" style={{ color: LT1 }}>欢迎回来</h2>
          <p className="text-[13px] mb-7" style={{ color: LT3 }}>请使用企业账号登录以继续使用平台</p>

          {/* Error alert */}
          {error && (
            <div className="flex items-start gap-2.5 rounded-xl mb-5"
              style={{ backgroundColor: "#FFF0F0", border: "1px solid #FFCCC7", padding: "12px 14px" }}>
              <AlertCircle size={15} color="#F53F3F" style={{ flexShrink: 0, marginTop: 1 }} />
              <span className="text-[13px]" style={{ color: "#F53F3F" }}>{error}</span>
            </div>
          )}

          {/* Account */}
          <div className="mb-4">
            <label className="block text-[13px] font-medium mb-1.5" style={{ color: "#4E5969" }}>账号</label>
            <input type="text" placeholder="请输入邮箱或用户名"
              value={account}
              onChange={e => { setAccount(e.target.value); if (aErr) setAErr(""); if (error) setError(""); }}
              onKeyDown={e => e.key === "Enter" && handleLogin()}
              className="h-10 rounded-xl px-3.5 text-[14px] transition-all"
              style={inputStyle(!!aErr)}
              onFocus={e => { Object.assign(e.currentTarget.style, inputStyle(!!aErr, true)); }}
              onBlur={e => { Object.assign(e.currentTarget.style, inputStyle(!!aErr, false)); }}
            />
            {aErr && <p className="text-[12px] mt-1.5" style={{ color: "#F53F3F" }}>{aErr}</p>}
          </div>

          {/* Password */}
          <div className="mb-4">
            <label className="block text-[13px] font-medium mb-1.5" style={{ color: "#4E5969" }}>密码</label>
            <div className="relative">
              <input type={showPw ? "text" : "password"} placeholder="请输入密码"
                value={password}
                onChange={e => { setPassword(e.target.value); if (pErr) setPErr(""); if (error) setError(""); }}
                onKeyDown={e => e.key === "Enter" && handleLogin()}
                className="h-10 rounded-xl pl-3.5 pr-10 text-[14px] transition-all"
                style={inputStyle(!!pErr)}
                onFocus={e => { Object.assign(e.currentTarget.style, inputStyle(!!pErr, true)); }}
                onBlur={e => { Object.assign(e.currentTarget.style, inputStyle(!!pErr, false)); }}
              />
              <button onClick={() => setShowPw(!showPw)}
                className="absolute right-3 top-2.5 transition-colors"
                style={{ background: "none", border: "none", cursor: "pointer", color: showPw ? LT3 : "#C9CDD4", padding: 0 }}
                onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = LT3; }}
                onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = showPw ? LT3 : "#C9CDD4"; }}>
                {showPw ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>
            {pErr && <p className="text-[12px] mt-1.5" style={{ color: "#F53F3F" }}>{pErr}</p>}
          </div>

          {/* Remember + Forgot */}
          <div className="flex items-center justify-between mb-6">
            <label className="flex items-center gap-2 cursor-pointer select-none" onClick={() => setRemember(!remember)}>
              <Checkbox on={remember} onChange={() => setRemember(!remember)} />
              <span className="text-[13px]" style={{ color: "#4E5969" }}>记住账号</span>
            </label>
            <button style={{ color: BLU, background: "none", border: "none", cursor: "pointer", fontSize: 13 }}>
              忘记密码
            </button>
          </div>

          {/* Login button */}
          <button onClick={handleLogin} disabled={loading}
            className="w-full h-10 rounded-xl text-white text-[14px] font-medium flex items-center justify-center gap-2 transition-all"
            style={{ backgroundColor: loading ? "#94BFFF" : BLU, border: "none", cursor: loading ? "not-allowed" : "pointer" }}
            onMouseEnter={e => { if (!loading) (e.currentTarget as HTMLButtonElement).style.filter = "brightness(1.08)"; }}
            onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.filter = ""; }}>
            {loading ? <><Loader2 size={15} className="animate-spin" />登录中...</> : "登录"}
          </button>

          {/* Network error demo hint */}
          <div className="mt-4 text-center">
            <span className="text-[11px]" style={{ color: "#C9CDD4" }}>
              输入密码 &ldquo;wrong&rdquo; 可演示错误状态
            </span>
          </div>

          {/* Footer */}
          <p className="text-[11px] text-center mt-7" style={{ color: "#C9CDD4" }}>
            如需账号，请联系管理员邀请 · AutoTest v2.4.1
          </p>
        </div>
      </div>
    </div>
  );
}

// src/pages/login/LoginPage.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'
import {
  Activity,
  AlertCircle,
  Bot,
  Bug,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  Globe2,
  Loader2,
  Timer,
  type LucideIcon,
} from '@lucide/vue'
import { useRoute, useRouter } from 'vue-router'

import { useLogin } from '@/features/auth-login'

const router = useRouter()
const route = useRoute()
const { loading, errorMessage, login } = useLogin()

const form = reactive({
  username: '',
  password: '',
})

const rememberAccount = ref(false)
const passwordVisible = ref(false)
const usernameError = ref('')
const passwordError = ref('')

const featureItems: Array<{
  icon: LucideIcon
  label: string
  description: string
  color: string
}> = [
  { icon: Bot, label: 'AI 用例生成', description: '需求驱动，自动生成', color: '#8b5cf6' },
  { icon: Globe2, label: '接口自动化', description: '场景化测试套件执行', color: '#165dff' },
  { icon: Activity, label: 'Web UI 自动化', description: '录制 + AI 优化断言', color: '#10b981' },
  { icon: Bug, label: '缺陷追踪', description: '发现到修复全流程', color: '#ef4444' },
  { icon: Timer, label: '任务调度', description: '定时执行和历史查看', color: '#f59e0b' },
  { icon: FileText, label: '智能报告', description: '多维度数据可视化', color: '#06b6d4' },
]

const executionLogs = [
  { tone: 'dim', text: '# 2026-07-07 14:30:01 触发: 定时调度' },
  { tone: 'ok', text: '✓ POST /api/v1/orders 200 142ms' },
  { tone: 'ok', text: '✓ GET /api/v1/orders/list 200 89ms' },
  { tone: 'ok', text: '✓ PUT /api/v1/orders/status 200 204ms' },
  { tone: 'fail', text: '✗ DELETE /api/v1/orders/52 500 3021ms' },
  { tone: 'warn', text: '△ 超时 > 3s，已推送企业微信告警通知' },
  { tone: 'ai', text: '◆ AI 分析: 建议增加重试断言，生成 3 个边界用例' },
  { tone: 'sum', text: '▸ 通过 47/48 失败 1 耗时 4m 22s' },
]

const stats = [
  { label: '今日执行', value: '236 次', tone: 'default' },
  { label: '整体通过率', value: '93.6%', tone: 'success' },
  { label: '在线 Runner', value: '6 个', tone: 'info' },
]

function resolveRedirect() {
  const redirect = route.query.redirect
  if (
    typeof redirect === 'string'
    && redirect.startsWith('/')
    && !redirect.startsWith('/login')
    && !redirect.startsWith('/workspaces/select')
  ) {
    return redirect
  }

  return '/config-center'
}

async function handleSubmit() {
  if (loading.value) {
    return
  }

  usernameError.value = form.username.trim() ? '' : '请输入账号'
  passwordError.value = form.password ? '' : '请输入密码'

  if (usernameError.value || passwordError.value) {
    return
  }

  try {
    await login({
      username: form.username.trim(),
      password: form.password,
    })
    await router.replace({
      path: '/workspaces/select',
      query: {
        redirect: resolveRedirect(),
      },
    })
  } catch {
    // useLogin exposes a stable, normalized error message for the page.
  }
}
</script>

<template>
  <main class="login-page">
    <section class="login-page__showcase" aria-label="平台能力展示">
      <div class="login-page__brand login-page__brand--dark">
        <span class="login-page__brand-mark">
          <FlaskConical class="login-page__brand-icon" />
        </span>
        <span class="login-page__brand-name">AutoTest</span>
        <span class="login-page__version">v2.4.1</span>
      </div>

      <div class="login-page__hero">
        <h1 class="login-page__hero-title">
          工程效率，<br>
          从测试开始
        </h1>
        <p class="login-page__hero-copy">
          AI 驱动的企业级自动化测试平台，<br>
          让质量保障不再成为交付的瓶颈
        </p>
      </div>

      <div class="login-page__features">
        <article
          v-for="item in featureItems"
          :key="item.label"
          class="login-page__feature"
          :style="{ '--feature-color': item.color }"
        >
          <span class="login-page__feature-icon">
            <component :is="item.icon" />
          </span>
          <span class="login-page__feature-copy">
            <strong>{{ item.label }}</strong>
            <small>{{ item.description }}</small>
          </span>
        </article>
      </div>

      <section class="login-page__terminal" aria-label="执行日志示例">
        <header class="login-page__terminal-header">
          <span class="login-page__terminal-dot login-page__terminal-dot--red" />
          <span class="login-page__terminal-dot login-page__terminal-dot--yellow" />
          <span class="login-page__terminal-dot login-page__terminal-dot--green" />
          <span class="login-page__terminal-title">execution.log</span>
          <span class="login-page__terminal-live">● LIVE</span>
        </header>
        <div class="login-page__terminal-body">
          <p
            v-for="(line, index) in executionLogs"
            :key="index"
            class="login-page__log-line"
            :class="`is-${line.tone}`"
          >
            {{ line.text }}
          </p>
        </div>
      </section>

      <dl class="login-page__stats">
        <div
          v-for="item in stats"
          :key="item.label"
          class="login-page__stat"
          :class="`is-${item.tone}`"
        >
          <dt>{{ item.label }}</dt>
          <dd>{{ item.value }}</dd>
        </div>
      </dl>
    </section>

    <section class="login-page__form-panel" aria-label="登录表单">
      <form class="login-page__form-card" @submit.prevent="handleSubmit">
        <div class="login-page__brand login-page__brand--light">
          <span class="login-page__brand-mark">
            <FlaskConical class="login-page__brand-icon" />
          </span>
          <span class="login-page__brand-name">AutoTest</span>
        </div>

        <div class="login-page__form-heading">
          <h2>欢迎回来</h2>
          <p>请使用企业账号登录以继续使用平台</p>
        </div>

        <div v-if="errorMessage" class="login-page__error" role="alert">
          <AlertCircle class="login-page__error-icon" />
          <span>{{ errorMessage }}</span>
        </div>

        <label class="login-page__field">
          <span class="login-page__field-label">账号</span>
          <input
            v-model="form.username"
            class="login-page__input"
            :class="{ 'is-invalid': usernameError }"
            autocomplete="username"
            placeholder="请输入邮箱或用户名"
            type="text"
            @input="usernameError = ''"
          >
          <span v-if="usernameError" class="login-page__field-error">{{ usernameError }}</span>
        </label>

        <label class="login-page__field">
          <span class="login-page__field-label">密码</span>
          <span class="login-page__password-wrap">
            <input
              v-model="form.password"
              class="login-page__input login-page__input--password"
              :class="{ 'is-invalid': passwordError }"
              autocomplete="current-password"
              placeholder="请输入密码"
              :type="passwordVisible ? 'text' : 'password'"
              @input="passwordError = ''"
              @keyup.enter="handleSubmit"
            >
            <button
              class="login-page__password-toggle"
              type="button"
              :aria-label="passwordVisible ? '隐藏密码' : '显示密码'"
              @click="passwordVisible = !passwordVisible"
            >
              <EyeOff v-if="passwordVisible" />
              <Eye v-else />
            </button>
          </span>
          <span v-if="passwordError" class="login-page__field-error">{{ passwordError }}</span>
        </label>

        <div class="login-page__form-options">
          <label class="login-page__remember">
            <input v-model="rememberAccount" type="checkbox">
            <span class="login-page__checkbox" aria-hidden="true" />
            <span>记住账号</span>
          </label>
          <button class="login-page__link-button" type="button">忘记密码</button>
        </div>

        <button
          class="login-page__submit"
          type="submit"
          :disabled="loading"
        >
          <Loader2 v-if="loading" class="login-page__submit-spinner" />
          <span>{{ loading ? '登录中...' : '登录' }}</span>
        </button>

        <p class="login-page__demo-hint">输入密码 “wrong” 可演示错误状态</p>
        <p class="login-page__hint">如需账号，请联系管理员邀请 · AutoTest v2.4.1</p>
      </form>
    </section>
  </main>
</template>

<style scoped>
.login-page {
  display: flex;
  min-height: 100dvh;
  overflow: hidden;
  background: #fff;
  font-family: var(--app-font-family);
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  text-rendering: geometricPrecision;
}

.login-page__showcase {
  display: flex;
  width: 58%;
  min-width: 640px;
  flex-direction: column;
  padding: 44px 52px;
  background: #0d1117;
}

.login-page__brand {
  display: flex;
  align-items: center;
  gap: 8.75px;
}

.login-page__brand--dark {
  height: 73.5px;
  align-items: flex-start;
}

.login-page__brand--light {
  height: 24.5px;
  margin-bottom: 35px;
}

.login-page__brand-mark {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex: 0 0 auto;
  border-radius: 12px;
  background: linear-gradient(135deg, #165dff, #4f8eff);
  color: #fff;
}

.login-page__brand--dark .login-page__brand-mark {
  width: 31.5px;
  height: 31.5px;
  border-radius: 11px;
}

.login-page__brand-icon {
  width: 18px;
  height: 18px;
}

.login-page__brand--light .login-page__brand-mark {
  width: 24.5px;
  height: 24.5px;
  border-radius: 7px;
}

.login-page__brand--light .login-page__brand-icon {
  width: 13px;
  height: 13px;
}

.login-page__brand-name {
  margin-top: 2.25px;
  color: #e6edf3;
  font-size: 18px;
  font-weight: 700;
  line-height: 27px;
}

.login-page__brand--light .login-page__brand-name {
  margin-top: 2.25px;
  color: #1d2129;
  font-size: 13px;
  font-weight: 600;
  line-height: 19.5px;
}

.login-page__version {
  margin-top: 5.5px;
  margin-left: 0;
  padding: 2.75px 8px;
  border: 1px solid #30363d;
  border-radius: 3.5px;
  background: #21262d;
  color: #7d8590;
  font-family: var(--app-font-family-mono);
  font-size: 10px;
  line-height: 15px;
}

.login-page__hero {
  height: 159.5px;
}

.login-page__hero-title {
  margin: 0;
  color: #e6edf3;
  font-size: 27px;
  font-weight: 600;
  letter-spacing: 0;
  line-height: 33.75px;
}

.login-page__hero-copy {
  max-width: 360px;
  margin: 10.5px 0 0;
  color: #7d8590;
  font-size: 14px;
  line-height: 22.75px;
}

.login-page__features {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 8.25px 8.75px;
  height: 214.5px;
  margin-bottom: 0;
}

.login-page__feature {
  display: flex;
  align-items: center;
  gap: 10.5px;
  height: 58px;
  min-width: 0;
  padding: 11.5px;
  border: 1px solid #21262d;
  border-radius: 11px;
  background: #161b22;
}

.login-page__feature-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24.5px;
  height: 24.5px;
  flex: 0 0 auto;
  border-radius: 7px;
  background: color-mix(in srgb, var(--feature-color) 13%, transparent);
  color: var(--feature-color);
}

.login-page__feature-icon svg {
  width: 14px;
  height: 14px;
}

.login-page__feature-copy {
  display: flex;
  min-width: 0;
  flex-direction: column;
  gap: 2px;
}

.login-page__feature-copy strong {
  overflow: hidden;
  color: #e6edf3;
  font-size: 12px;
  font-weight: 500;
  line-height: 18px;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.login-page__feature-copy small {
  overflow: hidden;
  color: #7d8590;
  font-size: 11px;
  line-height: 16px;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.login-page__terminal {
  display: flex;
  flex: 1;
  flex-direction: column;
  overflow: hidden;
  border: 1px solid #21262d;
  border-radius: 11px;
  background: #010409;
}

.login-page__terminal-header {
  display: flex;
  align-items: center;
  gap: 5.25px;
  height: 39px;
  padding: 8.75px 14px 9.75px;
  border-bottom: 1px solid #21262d;
  background: #161b22;
}

.login-page__terminal-dot {
  width: 8.75px;
  height: 8.75px;
  flex: 0 0 auto;
  border-radius: 999px;
}

.login-page__terminal-dot--red {
  background: #f85149;
}

.login-page__terminal-dot--yellow {
  background: #e3b341;
}

.login-page__terminal-dot--green {
  background: #3fb950;
}

.login-page__terminal-title {
  margin-left: 10.5px;
  color: #7d8590;
  font-family: var(--app-font-family-mono);
  font-size: 11px;
  line-height: 16.5px;
}

.login-page__terminal-live {
  margin-left: auto;
  padding: 2px 8px;
  border: 1px solid #2ea043;
  border-radius: 4px;
  background: #1b2a1b;
  color: #3fb950;
  font-family: var(--app-font-family-mono);
  font-size: 10px;
  line-height: 15px;
}

.login-page__terminal-body {
  display: flex;
  flex: 1;
  flex-direction: column;
  gap: 3.5px;
  overflow: hidden;
  padding: 14px;
  font-family: var(--app-font-family-mono);
  font-size: 11px;
  line-height: 16.5px;
}

.login-page__log-line {
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.login-page__log-line.is-dim {
  color: #7d8590;
}

.login-page__log-line.is-ok {
  color: #3fb950;
}

.login-page__log-line.is-fail {
  color: #f85149;
}

.login-page__log-line.is-warn {
  color: #e3b341;
}

.login-page__log-line.is-ai {
  color: #a78bfa;
}

.login-page__log-line.is-sum {
  color: #79c0ff;
}

.login-page__stats {
  display: flex;
  gap: 28px;
  height: 60.25px;
  margin: 0;
  padding: 0;
  padding-top: 17.5px;
}

.login-page__stat {
  display: flex;
  flex-direction: column-reverse;
  gap: 2px;
}

.login-page__stat dt {
  color: #7d8590;
  font-size: 10px;
  line-height: 16px;
}

.login-page__stat dd {
  margin: 0;
  color: #e6edf3;
  font-size: 17px;
  font-weight: 700;
  line-height: 24px;
}

.login-page__stat.is-success dd {
  color: #3fb950;
}

.login-page__stat.is-info dd {
  color: #79c0ff;
}

.login-page__form-panel {
  display: flex;
  width: 42%;
  min-width: 440px;
  align-items: center;
  justify-content: center;
  background: #fff;
}

.login-page__form-card {
  width: 100%;
  max-width: 360px;
  min-height: 442.25px;
  padding: 0 40px;
}

.login-page__form-heading {
  margin-bottom: 25.5px;
}

.login-page__form-heading h2 {
  margin: 0 0 5.25px;
  color: #1d2129;
  font-size: 24px;
  font-weight: 600;
  letter-spacing: 0;
  line-height: 36px;
}

.login-page__form-heading p {
  margin: 0;
  color: #86909c;
  font-size: 13px;
  line-height: 19.5px;
}

.login-page__error {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  margin-bottom: 20px;
  padding: 12px 14px;
  border: 1px solid #ffccc7;
  border-radius: 12px;
  background: #fff0f0;
  color: #f53f3f;
  font-size: 13px;
  line-height: 20px;
}

.login-page__error-icon {
  width: 15px;
  height: 15px;
  flex: 0 0 auto;
  margin-top: 2px;
}

.login-page__field {
  display: block;
  margin-bottom: 14px;
}

.login-page__field + .login-page__field {
  margin-bottom: 0;
}

.login-page__field-label {
  display: block;
  margin-bottom: 5.25px;
  color: #4e5969;
  font-size: 13px;
  font-weight: 500;
  line-height: 19.5px;
}

.login-page__input {
  width: 100%;
  height: 35px;
  padding: 0 13.25px;
  border: 1px solid #e5e6eb;
  border-radius: 11px;
  outline: none;
  background: #fff;
  color: #1d2129;
  font-size: 14px;
  line-height: 20px;
  transition: border-color 0.16s ease, box-shadow 0.16s ease;
}

.login-page__input::placeholder {
  color: #c9cdd4;
}

.login-page__input:focus {
  border-color: #165dff;
  box-shadow: 0 0 0 3px rgba(22, 93, 255, 0.1);
}

.login-page__input.is-invalid {
  border-color: #f53f3f;
}

.login-page__input.is-invalid:focus {
  border-color: #f53f3f;
  box-shadow: 0 0 0 3px rgba(245, 63, 63, 0.1);
}

.login-page__field-error {
  display: block;
  margin-top: 6px;
  color: #f53f3f;
  font-size: 12px;
  line-height: 18px;
}

.login-page__password-wrap {
  position: relative;
  display: block;
}

.login-page__input--password {
  padding-right: 36px;
}

.login-page__password-toggle {
  position: absolute;
  top: 50%;
  right: 10.5px;
  display: inline-flex;
  width: 16px;
  height: 16px;
  align-items: center;
  justify-content: center;
  padding: 0;
  border: 0;
  background: transparent;
  color: #c9cdd4;
  cursor: pointer;
  transform: translateY(-50%);
  transition: color 0.16s ease;
}

.login-page__password-toggle:hover {
  color: #86909c;
}

.login-page__password-toggle svg {
  width: 16px;
  height: 16px;
}

.login-page__form-options {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin: 14px 0 21.5px;
}

.login-page__remember {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  color: #4e5969;
  cursor: pointer;
  font-size: 13px;
  line-height: 20px;
  user-select: none;
}

.login-page__remember input {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
}

.login-page__checkbox {
  position: relative;
  display: inline-flex;
  width: 14px;
  height: 14px;
  align-items: center;
  justify-content: center;
  flex: 0 0 auto;
  border: 2px solid #c9cdd4;
  border-radius: 3.5px;
  transition: border-color 0.16s ease, background-color 0.16s ease;
}

.login-page__remember input:checked + .login-page__checkbox {
  border-color: #165dff;
  background: #165dff;
}

.login-page__remember input:checked + .login-page__checkbox::after {
  width: 7px;
  height: 4px;
  border-bottom: 1.5px solid #fff;
  border-left: 1.5px solid #fff;
  content: '';
  transform: translateY(-1px) rotate(-45deg);
}

.login-page__link-button {
  padding: 0;
  border: 0;
  background: transparent;
  color: #165dff;
  cursor: pointer;
  font-size: 13px;
  line-height: 20px;
}

.login-page__submit {
  display: inline-flex;
  width: 100%;
  height: 35px;
  align-items: center;
  justify-content: center;
  gap: 8px;
  border: 0;
  border-radius: 11px;
  background: #165dff;
  color: #fff;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  line-height: 21px;
  transition: filter 0.16s ease, background-color 0.16s ease;
}

.login-page__submit:hover:not(:disabled) {
  filter: brightness(1.08);
}

.login-page__submit:disabled {
  background: #94bfff;
  cursor: not-allowed;
}

.login-page__submit-spinner {
  width: 15px;
  height: 15px;
  animation: login-spin 0.8s linear infinite;
}

.login-page__hint {
  margin: 24.5px 0 0;
  color: #c9cdd4;
  font-size: 11px;
  line-height: 16.5px;
  text-align: center;
}

.login-page__demo-hint {
  margin: 14px 0 0;
  color: #c9cdd4;
  font-size: 11px;
  line-height: 16.5px;
  text-align: center;
}

@keyframes login-spin {
  to {
    transform: rotate(360deg);
  }
}

@media (max-width: 1080px) {
  .login-page__showcase {
    width: 54%;
    min-width: 540px;
    padding: 36px 36px;
  }

  .login-page__form-panel {
    width: 46%;
    min-width: 400px;
  }
}

@media (max-width: 860px) {
  .login-page {
    display: grid;
    min-height: 100dvh;
    place-items: center;
    padding: 24px;
    background: #0d1117;
  }

  .login-page__showcase {
    display: none;
  }

  .login-page__form-panel {
    width: min(100%, 440px);
    min-width: 0;
    border: 1px solid #21262d;
    border-radius: 20px;
    background: #fff;
    box-shadow: 0 24px 70px rgba(0, 0, 0, 0.28);
  }

  .login-page__form-card {
    max-width: none;
    min-height: 0;
    padding: 36px 32px;
  }
}
</style>
